# Default values for divvycloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
    imageName: divvycloud/divvycloud
    tag: v18.4.21
    pullPolicy: IfNotPresent

harvesters:
  replicaCount: 2

interfaceserver:
  replicaCount: 2
  service:
    externalPort: 8001

scheduler:
  replicaCount: 2

processor:
  replicaCount: 2

longharvester:
  replicaCount: 1

ondemand:
  replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
     #kubernetes.io/ingress.class: nginx,
     #     kubernetes.aio/tls-acme: "true"
  tls:
    enabled: false
    secretName: tls-cert
  path: /
  hosts:
    - divvy.priddle.co.nz

storage:
  size: 30Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
